/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as FundamentalsRouteImport } from './routes/fundamentals'
import { Route as CashRouteImport } from './routes/cash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const FundamentalsRoute = FundamentalsRouteImport.update({
  id: '/fundamentals',
  path: '/fundamentals',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/fundamentals': typeof FundamentalsRoute
  '/holdings': typeof HoldingsRoute
  '/login': typeof LoginRoute
  '/research': typeof ResearchRoute
  '/transactions': typeof TransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/fundamentals': typeof FundamentalsRoute
  '/holdings': typeof HoldingsRoute
  '/login': typeof LoginRoute
  '/research': typeof ResearchRoute
  '/transactions': typeof TransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/fundamentals': typeof FundamentalsRoute
  '/holdings': typeof HoldingsRoute
  '/login': typeof LoginRoute
  '/research': typeof ResearchRoute
  '/transactions': typeof TransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cash'
    | '/fundamentals'
    | '/holdings'
    | '/login'
    | '/research'
    | '/transactions'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cash'
    | '/fundamentals'
    | '/holdings'
    | '/login'
    | '/research'
    | '/transactions'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/cash'
    | '/fundamentals'
    | '/holdings'
    | '/login'
    | '/research'
    | '/transactions'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashRoute: typeof CashRoute
  FundamentalsRoute: typeof FundamentalsRoute
  HoldingsRoute: typeof HoldingsRoute
  LoginRoute: typeof LoginRoute
  ResearchRoute: typeof ResearchRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundamentals': {
      id: '/fundamentals'
      path: '/fundamentals'
      fullPath: '/fundamentals'
      preLoaderRoute: typeof FundamentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashRoute: CashRoute,
  FundamentalsRoute: FundamentalsRoute,
  HoldingsRoute: HoldingsRoute,
  LoginRoute: LoginRoute,
  ResearchRoute: ResearchRoute,
  TransactionsRoute: TransactionsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
